# create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Yulinar Nur 2",
    "email": "admin1@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
# get all users
GET http://localhost:5000/users

###
// Get single User
GET http://localhost:5000/users/02c9f7ee-83fd-4150-ad12-3c71ce481dec

###
// Update Usser
PATCH http://localhost:5000/users/af876112-11b9-4317-9e5b-ef872542605f
Content-Type: application/json

{
    "name": "Yulinar Nur 2 Update",
    "email": "admin1@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

###
// Delete User
DELETE  http://localhost:5000/users/af876112-11b9-4317-9e5b-ef872542605f

###
//Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rahmawati@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me

###
// Logout user
DELETE http://localhost:5000/logout



###
// get Data Cars
GET http://localhost:5000/cars